name: Coverage and Sanitisation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make test
      run: make -C 3_Implementation/ test
    - name: coverage
      run: make -C 3_Implementation/ coverage
    - name: sanitize check
      run: make -C 3_Implementation/ sanitize_check
